### ISSUE TITLE
Allow encoding specification - UnicodeEncodeError: 'charmap' codec can't encode character

### ISSUE THREAD

**Issue by JMSS-Unknown** [dflook/python-minifier#2]
I was trying to minify a file that contains lines as below in utf-8 format:
`print("≡")`

Currently it fails with
`UnicodeEncodeError: 'charmap' codec can't encode character '\u2030' in position 8: character maps to <undefined>`

A fix would be if the encoding is specified when the file is opened
`with open('filename', 'w', encoding='utf-8') as f:`

Maybe allow something like?
`pyminifer --encoding 'utf-8' file.py`

**Comment by dflook** [comment]
Thanks for creating an issue. What version of python are you using?

**Comment by JMSS-Unknown** [comment]
I checked with both python 3.5 and 3.6

**Comment by JMSS-Unknown** [comment]
It looks like it works correctly with python 3.6. The issue is I'm redirecting stdout to a file with the wrong encoding. 

My bad.

**Comment by dflook** [comment]
No problem, glad it works for you :)

**Comment by JMSS-Unknown** [comment]
Thanks for the quick reply.
