### ISSUE TITLE
Function names are not changed for some files

### ISSUE THREAD

**Issue by fersarr** [dflook/python-minifier#22]
Hi, thanks for this really useful tool.

I have been testing it with some of my files and I see that for some files, the function names get changed but for some they don't. Unfortunately I can't paste the one that doesn't get the names changed. Do you have any reason in mind as to why that could be happening? If not, I will put more work into trying to create a working example that I can share.

For this file, however, the functions _do_ get renamed:

```
# test_file.py
global_var = 3

def test_function(prep_text, entites):
    '''
    test comment
    '''
    # single line comment
    test_var_name = {
        'blabla': '1',
        'blabla2': '2'
    }

    myset = {'one', 'two', 'three'}
    print(myset)

    return test_var_name


def test_func_1(var1):
    print('bla')

def test_func_2(var2):
    test_func_1(var1)

def test_func_3(var1):
    test_func_2('blabla')
```

```
$ pyminify --remove-literal-statements --rename-globals --no-hoist-literals test_file.py
C=print
D=3
def E(prep_text,entites):A={'blabla':'1','blabla2':'2'};B={'one','two','three'};C(B);return A
def A(var1):C('bla')
def B(var2):A(var1)
def F(var1):B('blabla')
```

**Comment by fersarr** [comment]
hm interesting, local variables are also not getting renamed in that bigger file I mentioned.

**Comment by dflook** [comment]
Hi @fersarr, There are two likely reasons for this:

- The module uses `vars()`, `exec()`, `locals()`, `globals()` or `eval()`, which disables all renaming.

- `from <module> import *` is used, which disables renaming of globals. 

Can you narrow it down to one of these?

**Comment by fersarr** [comment]
aha! perfect. Yes, I removed a `from <module> import *` and it started renaming everything. Thanks a lot!
