### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by NaziYeeter** [dflook/python-minifier#26]
Can we have unreadable like unicode or byte variable renames instead of abc

And also and option for 1 line instead of new lines

**Comment by xcodz-dot** [comment]
1 liners is not possible in python for most of the time because of colons and indentation used for blocks. though semicolons in certain blocks is possible.

Check here #25

**Comment by dflook** [comment]
Obfuscation isn't a goal of this project, so unreadable names is out of scope. It would also be trivial to reverse by running it through python-minifier again.

When renaming, python-minifier already uses the full range of available single byte characters for maximum space saving.
