### ISSUE TITLE
Inconsistency between stdin and file input

### ISSUE THREAD

**Issue by clbarnes** [dflook/python-minifier#40]
`sys.stdin.read()` reads a UTF-8 string, but a file is opened in binary mode (and therefore reads `bytes`). Either bytes should be read from `sys.stdin.buffer`, or the file should be opened in text mode.

**Comment by dflook** [comment]
Hi @clbarnes, do you have an example where this causes a problem?

**Comment by clbarnes** [comment]
No particular examples - does this inconsistency solve any problems itself? The default python source encoding is UTF-8, but other encodings are allowed, so they should probably both return `bytes`, I guess?

**Comment by dflook** [comment]
This has been fixed in 2.6.0, stdin is now read as bytes.
