### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by NadieFiind** [dflook/python-minifier#57]
An [issue](https://github.com/dflook/python-minifier/issues/2) related to this is already closed. But it seems that it is not yet completely fixed.

The error occurs on emojis.

This is the exact command I used:
```bash
pyminify folder --in-place --remove-literal-statements
```

**Versions:**
- python 3.10.7
- python-minifier 2.6.0

**Comment by dflook** [comment]
Hello @NadieFiind, can you share the source you are trying to minify and the output from pyminify?

**Comment by dflook** [comment]
Thanks. I'm not familiar with windows but it looks like the python uses a different encoding instead of utf-8.
Could you set the environment variable `PYTHONUTF8=1` and see if it works?

**Comment by NadieFiind** [comment]
@dflook Oh yes, it works now. Thanks!
