### ISSUE TITLE
Minor Issue - If the code has © symbol it won't run after using minifier...

### ISSUE THREAD

**Issue by TheWicklowWolf** [dflook/python-minifier#59]
When I try to run the converted code it returns the following error:
(unicode error) 'utf-8' codec can't decode byte 0xa9 in position 29: invalid start byte

I had a string that had a copyright symbol, I've remove the symbol and it works.

Thanks

**Comment by dflook** [comment]
Hello @TheWicklowWolf, what are the versions of python and python-minifier that you are using?

**Comment by TheWicklowWolf** [comment]
python 3.11
python-minifier 2.7

**Comment by dflook** [comment]
I can't reproduce this in my linux or macos environments. Are you using windows? This could be related to #57

**Comment by TheWicklowWolf** [comment]
Yes using Windows, that makes sense. Thanks for you help
